### ISSUE TITLE
Different collision operator

### ISSUE THREAD

**Issue by benoit-sbr** [vavrines/Kinetic.jl#18]
Hi,

I am interested in equations similar to the nonlinear Boltzmann equation, but with what we could call growth or fragmentation events (they emerge from problems in biology), that is:
$
\frac{\partial f}{\partial t}+ \mathbf v \cdot \nabla_\mathbf x f  = Q(f),
$
where the collision operator $Q$ is more general than in [the documentation](https://xiaotianbai.com/Kinetic.jl/dev/physics/).
More precisely, $Q$ involves the integral of - for instance - $f(v-Kv')f(v')$ against a given kernel for a constant $K$.

Is the Kinetic.jl library adapted to such problems?

**Comment by vavrines** [comment]
@benoit-sbr 

Hi, it's hard to say without a detailed example. Does v' have a similar meaning as the classical Boltzmann equation? 
I find this integral interesting. Maybe you can guide me to a paper?

**Comment by benoit-sbr** [comment]
@vavrines thank you for your interest! No the meaning is different. These problems are similar to the [Smoluchowski equation](https://en.wikipedia.org/wiki/Smoluchowski_coagulation_equation).

**Comment by vavrines** [comment]
@benoit-sbr Okay now I get what you mean. Yes the population balance equation has very similar structure as the Boltzmann, and thus the data structure can be shared. There is no function that can be directly applied now, but it seems not very hard to extend the functionality. You may refer this repo (https://github.com/yewalenikhil65/Population-balance-equation). Also if you want to write some codes on top of Kinetic, I'm glad to provide support.

**Comment by benoit-sbr** [comment]
@vavrines OK I will browse the code and try to find my way around. Not sure I can help to code though!
