### ISSUE TITLE
Calculation problem about normal shock structure of mixed gas

### ISSUE THREAD

**Issue by zhangzhg0508** [vavrines/Kinetic.jl#19]
Hi,
I used mixture_shock.jl under Kinetic.jl/example/ for mixed gas calculation. 
The calculated parameter file has been partially modified. 
mixture_shock.jl has also been partially modified. 
But my calculation results are different from the results in the literature, I don't know what went wrong.
I hope to get help. Thank you very much.

The parameter file and mixture_shock.jl file are as follows.
[mixture_shock.zip](https://github.com/vavrines/Kinetic.jl/files/8631382/mixture_shock.zip)

Calculation A,B rho results for attached files
![plot_1](https://user-images.githubusercontent.com/16329328/166927662-29644d90-cadd-4028-a783-7eeb0a8629fe.png)

Calculation results of the paper
A unified gas-kinetic scheme for multiscale and multicomponent flow transport∗
![paper](https://user-images.githubusercontent.com/16329328/166929024-e3ac9e4d-389a-45a8-bccc-e1a7949ae1ca.png)

**Comment by vavrines** [comment]
With the latest KitBase v0.8.3, you can find the latest example [mixture_shock.jl](https://github.com/vavrines/Kinetic.jl/blob/master/example/mixture_shock.jl).
The results will be slightly different from the paper as the spectral method for the full Boltzmann collision integral hasn't been implemented here yet.

**Comment by zhangzhg0508** [comment]
My question is solved perfectly.
Thank you very much!
