### ISSUE TITLE
Problem with running examples

### ISSUE THREAD

**Issue by floatingCatty** [vavrines/Kinetic.jl#24]
Hi I just try this software. Installed it and try to run some examples.

I have done julia Pkg test, it successed. But when I run Plasma_briowu_1d.jl, the following error arise:

ERROR: LoadError: TaskFailedException
Stacktrace:
 [1] wait
   @ .\task.jl:345 [inlined]
 [2] threading_run(fun::var"#291#threadsfor_fun#2"{var"#291#threadsfor_fun#1#3"{Matrix{Float64}, Matrix{Float64}, UnitRange{Int64}}}, static::Bool)
   @ Base.Threads .\threadingconstructs.jl:38
 [3] macro expansion
   @ .\threadingconstructs.jl:89 [inlined]
 [4] macro expansion
   @ D:\Softwares\Julia-1.8.5\.julia\packages\Kinetic\LEatc\example\plasma_briowu_1d.jl:77 [inlined]
 [5] top-level scope
   @ D:\Softwares\Julia-1.8.5\.julia\packages\ProgressMeter\sN2xr\src\ProgressMeter.jl:938

    nested task error: UndefVarError: step! not defined
    Stacktrace:
     [1] macro expansion
       @ D:\Softwares\Julia-1.8.5\.julia\packages\Kinetic\LEatc\example\plasma_briowu_1d.jl:78 [inlined]
     [2] (::var"#291#threadsfor_fun#2"{var"#291#threadsfor_fun#1#3"{Matrix{Float64}, Matrix{Float64}, UnitRange{Int64}}})(tid::Int64; onethread::Bool)
       @ Main .\threadingconstructs.jl:84
     [3] #291#threadsfor_fun
       @ .\threadingconstructs.jl:51 [inlined]
     [4] (::Base.Threads.var"#1#2"{var"#291#threadsfor_fun#2"{var"#291#threadsfor_fun#1#3"{Matrix{Float64}, Matrix{Float64}, UnitRange{Int64}}}, Int64})()
       @ Base.Threads .\threadingconstructs.jl:30
in expression starting at D:\Softwares\Julia-1.8.5\.julia\packages\Kinetic\LEatc\example\plasma_briowu_1d.jl:12

I am new to julia language also, could there be some helps in this issue ?

**Comment by vavrines** [comment]
I just tested it and can't reproduce the error.
Can you check the current package version of Kinetic/KitBase you installed? This can be done by typing `]` in Julia REPL and in the Pkg mode typing `status`.

**Comment by floatingCatty** [comment]
Okay. the status looks like this:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/64253517/219865618-03ae550f-af72-497b-b32f-4fd7fb589e0f.png">

**Comment by vavrines** [comment]
The status looks good.
Then are you sure you are running the correct script? The error message says
`@ D:\Softwares\Julia-1.8.5.julia\packages\Kinetic\LEatc\example\plasma_briowu_1d.jl:77 [inlined]`, but the code is not even as lengthy as 77 lines, see https://github.com/vavrines/Kinetic.jl/blob/master/example/plasma/briowu_1d.jl
The codebase is not tested on Windows now so I can't promise it. But the error here is weird.

**Comment by floatingCatty** [comment]
Okay, I will try this code on linux shortly. Thanks.

Tianbai Xiao ***@***.***> 于 2023年2月18日周六 下午9:06写道：

**Comment by floatingCatty** [comment]
By the way, is the python wrapper has all the function as the julia
version? If so I will use the python one instead. Thanks !

Austin Zhou ***@***.***> 于2023年2月18日周六 21:25写道：

**Comment by vavrines** [comment]
I would strongly encourage using native Julia codes due to the current limitations held by PyCall and some inconsistent behaviors between Python and Julia.
