### ISSUE TITLE
Applicability of Kinetic in PLASMA flow control

### ISSUE THREAD

**Issue by Badtreater** [vavrines/Kinetic.jl#25]
**Dear researchers and developers,** 
thank you so much for providing the open-source simulation codes. It is my honor to write this letter to you guys who are expanding into new fields. I am a novice in PLASMA research and working hard to complete my doctoral studies.However, due to my poor ability on programming of finite element solvers, it has been hard to complete the simulation code of PLASMA completely on my own. To be honest, I was very excited when I first saw **Kinetic**. I thought it might help me to supplement my lack of simulation.
To get back to the point, I hope to use **Kinetic** to complete the simulation work in the literature[1], but unfortunately, due to a lack of understanding of the underlying solver, I am unable to make a judgment on whether **Kinetic** can correctly complete this simulation process. I am eager to receive your answers on the applicability of the **Kinetic** underlying solver to the simulation of PLASMA flow control actuators. If the work can proceed, I also hope to include the reference of CFDWARP in my own paper when publishing articles in the future. Thank you so much. 

Reference
[1]Kunwar Pal Singh, Subrata Roy; Modeling plasma actuators with air chemistry for effective flow control. Journal of Applied Physics 15 June 2007; 101 (12): 123308. https://doi.org/10.1063/1.2749467

**Comment by vavrines** [comment]
Although I am not familiar with the reference you attached, it seems quite engineering-oriented which may be beyond the current scope of Kinetic.
Kinetic can deal with fully ionized plasma flows by solving the Vlasov equation. An example can be found here (https://github.com/vavrines/Kinetic.jl/blob/master/example/plasma/briowu_1d.jl).
Neither partially ionized plasma model or ionization model has been implemented yet.

**Comment by Badtreater** [comment]
Thank you very much for your reply. The article in the reference is indeed a flow control oriented simulation study. Perhaps I need to further explore and find solutions. Thank you very much. Finally, could I ask another question? You mentioned in your letter that the PLASMA mathematical model for partial ionization has not yet been established. Can there be accurate relevant literature for me to refer to and learn about this conclusion? Thank you.


| |
Tayir
|
|
***@***.***
|
On 7/2/2023 15:39，Tianbai ***@***.***> wrote：

Although I am not familiar with the reference you attached, it seems quite engineering-oriented which may be beyond the current scope of Kinetic.
Kinetic can deal with fully ionized plasma flows by solving the Vlasov equation. An example can be found here (https://github.com/vavrines/Kinetic.jl/blob/master/example/plasma/briowu_1d.jl).
Neither partially ionized plasma model or ionization model has been implemented yet.

**Comment by vavrines** [comment]
Ionization is a hard issue from a kinetic perspective.
Some preliminary attempts can be found in (Meier, E. T., and U. Shumlak. "A general nonlinear fluid model for reacting plasma-neutral mixtures." Physics of Plasmas 19, no. 7 (2012)).

**Comment by Badtreater** [comment]
Thank you so much for your suggestions. May I ask your nationality? I guess you're Chinese, so am I. Anyway, thank you！！！
| |
Tayir
|
|
***@***.***
|
On 7/2/2023 15:53，Tianbai ***@***.***> wrote：

Ionization is a hard issue from a kinetic perspective.
Some preliminary attempts can be found in (Meier, E. T., and U. Shumlak. "A general nonlinear fluid model for reacting plasma-neutral mixtures." Physics of Plasmas 19, no. 7 (2012)).
