### ISSUE TITLE
About shock example run

### ISSUE THREAD

**Issue by zhangzhg0508** [vavrines/Kinetic.jl#5]
Hello!

How to run mixture shock structure example?
Thank you!

**Comment by vavrines** [comment]
> Hello!
> 
> How to run mixture shock structure example?
> Thank you!

You could check the plasma case (https://github.com/vavrines/Kinetic.jl/blob/master/example/plasma_briowu_1d.jl).
It has two species, i.e. ions and electrons.
Clone the repository, `cd` the example folder, and execute `julia plasma_briowu_1d.jl`.

**Comment by zhangzhg0508** [comment]
Thank you!
